// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL3t04GpWrHXroRUYvqyeofkcBT15rPxE',
    appId: '1:225672136404:web:87d0b75918c69b66aedd41',
    messagingSenderId: '225672136404',
    projectId: 'todo-flutter-app-e0f55',
    authDomain: 'todo-flutter-app-e0f55.firebaseapp.com',
    storageBucket: 'todo-flutter-app-e0f55.firebasestorage.app',
    measurementId: 'G-2TLH3NC1BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK4z8AtOKqJG5KefiiXrz8MaO1JlVkApc',
    appId: '1:225672136404:android:9459ffae21eba9ceaedd41',
    messagingSenderId: '225672136404',
    projectId: 'todo-flutter-app-e0f55',
    storageBucket: 'todo-flutter-app-e0f55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFtrmMEJNMxI0uR0PDRddYy_hn-_TAqy0',
    appId: '1:225672136404:ios:1ee01eef8da713e4aedd41',
    messagingSenderId: '225672136404',
    projectId: 'todo-flutter-app-e0f55',
    storageBucket: 'todo-flutter-app-e0f55.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFtrmMEJNMxI0uR0PDRddYy_hn-_TAqy0',
    appId: '1:225672136404:ios:1ee01eef8da713e4aedd41',
    messagingSenderId: '225672136404',
    projectId: 'todo-flutter-app-e0f55',
    storageBucket: 'todo-flutter-app-e0f55.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL3t04GpWrHXroRUYvqyeofkcBT15rPxE',
    appId: '1:225672136404:web:29fa0b612e689534aedd41',
    messagingSenderId: '225672136404',
    projectId: 'todo-flutter-app-e0f55',
    authDomain: 'todo-flutter-app-e0f55.firebaseapp.com',
    storageBucket: 'todo-flutter-app-e0f55.firebasestorage.app',
    measurementId: 'G-PVQ2PFTHLL',
  );
}
